// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oywnoebuanmnydyauail.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95d25vZWJ1YW5tbnlkeWF1YWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NjUwNjQsImV4cCI6MjA1MjM0MTA2NH0.xgdlx3lugp4wcQougRDuYj8BDzdDvmH4ao7uUNhV-Fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);